package tst.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import org.apache.ibatis.annotations.Param;
import tst.mybatis.model.Testtable;
import tst.mybatis.model.TesttableExample;

@Mapper
public interface TesttableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TESTTABLE
     *
     * @mbg.generated Thu Mar 29 23:37:33 EEST 2018
     */
    long countByExample(TesttableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TESTTABLE
     *
     * @mbg.generated Thu Mar 29 23:37:33 EEST 2018
     */
    int deleteByExample(TesttableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TESTTABLE
     *
     * @mbg.generated Thu Mar 29 23:37:33 EEST 2018
     */
    int deleteByPrimaryKey(Integer column1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TESTTABLE
     *
     * @mbg.generated Thu Mar 29 23:37:33 EEST 2018
     */
    int insert(Testtable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TESTTABLE
     *
     * @mbg.generated Thu Mar 29 23:37:33 EEST 2018
     */
    int insertSelective(Testtable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TESTTABLE
     *
     * @mbg.generated Thu Mar 29 23:37:33 EEST 2018
     */
    List<Testtable> selectByExample(TesttableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TESTTABLE
     *
     * @mbg.generated Thu Mar 29 23:37:33 EEST 2018
     */
    Testtable selectByPrimaryKey(Integer column1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TESTTABLE
     *
     * @mbg.generated Thu Mar 29 23:37:33 EEST 2018
     */
    int updateByExampleSelective(@Param("record") Testtable record, @Param("example") TesttableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TESTTABLE
     *
     * @mbg.generated Thu Mar 29 23:37:33 EEST 2018
     */
    int updateByExample(@Param("record") Testtable record, @Param("example") TesttableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TESTTABLE
     *
     * @mbg.generated Thu Mar 29 23:37:33 EEST 2018
     */
    int updateByPrimaryKeySelective(Testtable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TESTTABLE
     *
     * @mbg.generated Thu Mar 29 23:37:33 EEST 2018
     */
    int updateByPrimaryKey(Testtable record);
}