package psk.Mybatis.models;

public class CustomersAccountsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMERS_ACCOUNTS.CUSTOMER_ID
     *
     * @mbg.generated Fri Apr 06 20:27:02 EEST 2018
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMERS_ACCOUNTS.ACCOUNTS_ID
     *
     * @mbg.generated Fri Apr 06 20:27:02 EEST 2018
     */
    private Integer accountsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMERS_ACCOUNTS.CUSTOMER_ID
     *
     * @return the value of PUBLIC.CUSTOMERS_ACCOUNTS.CUSTOMER_ID
     *
     * @mbg.generated Fri Apr 06 20:27:02 EEST 2018
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMERS_ACCOUNTS.CUSTOMER_ID
     *
     * @param customerId the value for PUBLIC.CUSTOMERS_ACCOUNTS.CUSTOMER_ID
     *
     * @mbg.generated Fri Apr 06 20:27:02 EEST 2018
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMERS_ACCOUNTS.ACCOUNTS_ID
     *
     * @return the value of PUBLIC.CUSTOMERS_ACCOUNTS.ACCOUNTS_ID
     *
     * @mbg.generated Fri Apr 06 20:27:02 EEST 2018
     */
    public Integer getAccountsId() {
        return accountsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMERS_ACCOUNTS.ACCOUNTS_ID
     *
     * @param accountsId the value for PUBLIC.CUSTOMERS_ACCOUNTS.ACCOUNTS_ID
     *
     * @mbg.generated Fri Apr 06 20:27:02 EEST 2018
     */
    public void setAccountsId(Integer accountsId) {
        this.accountsId = accountsId;
    }
}