package tst.mybatis.model;

public class Testtable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TESTTABLE.COLUMN_1
     *
     * @mbg.generated Thu Mar 29 23:37:33 EEST 2018
     */
    private Integer column1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TESTTABLE.COLUMN_2
     *
     * @mbg.generated Thu Mar 29 23:37:33 EEST 2018
     */
    private String column2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TESTTABLE.COLUMN_1
     *
     * @return the value of PUBLIC.TESTTABLE.COLUMN_1
     *
     * @mbg.generated Thu Mar 29 23:37:33 EEST 2018
     */
    public Integer getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TESTTABLE.COLUMN_1
     *
     * @param column1 the value for PUBLIC.TESTTABLE.COLUMN_1
     *
     * @mbg.generated Thu Mar 29 23:37:33 EEST 2018
     */
    public void setColumn1(Integer column1) {
        this.column1 = column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TESTTABLE.COLUMN_2
     *
     * @return the value of PUBLIC.TESTTABLE.COLUMN_2
     *
     * @mbg.generated Thu Mar 29 23:37:33 EEST 2018
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TESTTABLE.COLUMN_2
     *
     * @param column2 the value for PUBLIC.TESTTABLE.COLUMN_2
     *
     * @mbg.generated Thu Mar 29 23:37:33 EEST 2018
     */
    public void setColumn2(String column2) {
        this.column2 = column2;
    }
}